#!/usr/bin/env bash

# Copyright  2024 - present  Dr Tim Brunne (Munich)
#
# This file is part of XFakturist, <https://github.com/drbrnn/XFakturist>.
#
# XFakturist is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# XFakturist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with XFakturist.  If not, see <http://www.gnu.org/licenses/>.


# purpose:  Download all required software components for electronic invoice
#           validation and visualisation, copy all files to directory `kosit-xr`
#           rename directories and create a few symbolic links.
#
#           The following terminal commands depend on software downloaded to
#           directory `kosit-xr`:
#
#               xr-validate   : check hundreds of XML invoice validation rules
#                               and create a corresponding validation report,
#                               in HTML format
#
#               xr-convert    : to improve human readability, create HTML and
#                               PDF files to display the information content of
#                               an XML invoice
#
#           The downloaded software libraries are provided and licensed
#           to the end user by the following entities: the German government
#           authorities “Institut für IT-Standardisierung – Koordinierungsstelle
#           für IT-Standards für den Bund und die Länder” (KoSIT), “Kassen- und
#           Rechnungswesen des Bundes” (KKR), the British software firm Saxonica,
#           and the Apache Foundation.
#           

# to update the variables below, check for KoSIT updates here:
#
#   https://github.com/itplr-kosit/validator/releases
#   https://github.com/itplr-kosit/validator-configuration-xrechnung/releases
#   (old: https://github.com/itplr-kosit/xrechnung-visualization/releases)
#   https://projekte.kosit.org/xrechnung/xrechnung-visualization/-/tags
#
# to update the variables below, check for SAXONICA updates here:
#
#   https://www.saxonica.com/download/java.xml
#
# to update the variables below, check for APACHE FOP updates here:
#
#   https://www.apache.org/dyn/closer.cgi/xmlgraphics/fop
#   https://dlcdn.apache.org/xmlgraphics/fop/binaries/
#
# see also: https://github.com/itplr-kosit/validator-configuration-xrechnung/blob/master/docs/usage.md

KOSIT_VALIDATOR_VERSION="1.6.1"
KOSIT_VALIDATOR_CONFIGURATION_RELEASE="2026-01-31"
KOSIT_VISUALIZATION_VERSION="2026-01-31"
KOSIT_XRECHNUNG_STANDARD="3.0.2"
SAXON_RELEASE="12-9"
FOP_VERSION="2.11"


# (-1-) specify download locations of ZIP files from KoSIT et al.
#
# [1] KoSIT validator
# [2] KoSIT validator configuration (for XRechnung and other EN16931 compliant invoices)
# [3] KoSIT invoice visualisation (for XRechnung and other EN16931 compliant invoices)
# [4] Saxonica Saxon Home Edition Java archive (in particular, for the XSL translations required for visualisation)
# [5] Apache Formatting Objects Processor (FOP)

ZIPFILE_NAMES[1]="validator-${KOSIT_VALIDATOR_VERSION}"
ZIPFILE_NAMES[2]="xrechnung-${KOSIT_XRECHNUNG_STANDARD}-validator-configuration-${KOSIT_VALIDATOR_CONFIGURATION_RELEASE}"
ZIPFILE_NAMES[3]="xrechnung-visualization-${KOSIT_VISUALIZATION_VERSION}"
ZIPFILE_NAMES[4]="SaxonHE${SAXON_RELEASE}J"
ZIPFILE_NAMES[5]="fop-${FOP_VERSION}-bin"

URL_BASENAMES[1]="https://github.com/itplr-kosit/validator/releases/download/v${KOSIT_VALIDATOR_VERSION}"
URL_BASENAMES[2]="https://github.com/itplr-kosit/validator-configuration-xrechnung/releases/download/v${KOSIT_VALIDATOR_CONFIGURATION_RELEASE}/"
URL_BASENAMES[3]="https://projekte.kosit.org/xrechnung/xrechnung-visualization/-/archive/v${KOSIT_VISUALIZATION_VERSION}"
URL_BASENAMES[4]="https://github.com/Saxonica/Saxon-HE/releases/download/SaxonHE${SAXON_RELEASE}"
URL_BASENAMES[5]="https://dlcdn.apache.org/xmlgraphics/fop/binaries"


# (-2-) download ZIP files

rm -rf kosit-xr
if [ ! -d kosit-xr ] ; then mkdir kosit-xr ; fi
if [ ! -d downloads ] ; then mkdir downloads ; fi

for i in 1 2 3 4 5
do
    # FIXME: add hash sum or signature checks to verify integrity of downloads

    curl -L ${URL_BASENAMES[i]}/${ZIPFILE_NAMES[i]}.zip --output downloads/${ZIPFILE_NAMES[i]}.zip
    unzip downloads/${ZIPFILE_NAMES[i]}.zip -d kosit-xr/${ZIPFILE_NAMES[i]}

    # as of Feb 2026, the validator standalone JAR was removed from the ZIP file
    if [ $i == 1 ] ; then
        S_JAR="${ZIPFILE_NAMES[1]}-standalone.jar"
        curl -L ${URL_BASENAMES[1]}/${S_JAR} --output downloads/${S_JAR}
        cp -p downloads/${S_JAR} kosit-xr/${ZIPFILE_NAMES[i]}/
    fi
done


# (-3-) create generic-name directories and soft links

cd kosit-xr

ln -f -s ${ZIPFILE_NAMES[1]}/validator-${KOSIT_VALIDATOR_VERSION}-standalone.jar validator.jar
ln -f -s ${ZIPFILE_NAMES[2]} validator-configuration
mv ${ZIPFILE_NAMES[3]}/*/* ${ZIPFILE_NAMES[3]}/
mv ${ZIPFILE_NAMES[3]}/conf conf
mv ${ZIPFILE_NAMES[3]}/src/xsl xsl
mv ${ZIPFILE_NAMES[3]}/src/xsd xsd
ln -f -s ${ZIPFILE_NAMES[4]}/saxon-he-$(echo ${SAXON_RELEASE} | sed 's/-/./').jar saxon-he.jar
mv ${ZIPFILE_NAMES[5]}/*/* ${ZIPFILE_NAMES[5]}/
mv ${ZIPFILE_NAMES[5]}/fop fop
